version: "1.0"

services:

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   depends_on:
  #     # - scraper
  #     # - trends
  #     - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./laravel-keyword-planner:/var/www/planner
      - ./certbot-www/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      # - scraper
      # - trends
      - planner

  scraper:
    build:
      context: ./php-scraper
      dockerfile: Dockerfile
    ports:
      - "25000:3000"
    volumes:
      - ./php-scraper:/app
    command: sh -c "npm install && npm start --host=0.0.0.0 --port=3000"
    restart: unless-stopped

  trends:
    build:
      context: ./pytrends-api
      dockerfile: Dockerfile
    ports:
      - "25100:8000"
    volumes:
      - ./pytrends-api:/app

  planner:
    build:
      context: ./laravel-keyword-planner
      dockerfile: Dockerfile
    ports:
      - "29000:9000"
    volumes:
      - ./laravel-keyword-planner:/var/www/planner
      
  frontend:
    build:
      context: ./laravel-keyword-planner
      dockerfile: frontend.Dockerfile
    volumes:
      - ./laravel-keyword-planner:/var/www/planner
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

    command: sh -c "npm install --legacy-peer-deps && npm run dev"

      
